#!/bin/sh
#
# Run node-webkit from the command line on a Mac
#
# If the first argument is -X, run the executable directly,
# which is useful to see error messages.

# adjust to local install
NWAPP=/Applications/node-webkit.app
# alternative if you have multiple versions:
#VERSION=0.9.2
#NWDIR=/Users/mbl/Dev/Tools/Web\ browsers/Node-WebKit
#NWAPP=$NWDIR/node-webkit-v$VERSION/node-webkit.app

# do not change below this
NW=$NWAPP/Contents/MacOS/node-webkit

# if the first argument is -X, run NW instead of open NWAPP
# (useful, e.g. to catch errors that occur at startup)
if [ $# -ge 1 -a "$1" = "-X" ]
then
        shift
        echo "running $NW"

        if [ $# -ge 1 -a -d "$1" -a -f "$1/package.json" ]
        then
                # node-webkit wants a full path for the package
#               case $1 in
#                       /*) PACKAGE=$1 ;;
#                       *) PACKAGE=`pwd`/$1 ;;
#               esac
# Do this instead because otherwise the app protocol does not seem to work!
                cd $1
                PACKAGE=.
###
                shift
                "$NW" "$PACKAGE" $*
        else
                "$NW" `pwd` $*
        fi
        exit 0
fi

# if there are arguments, look at the first one.
# if it is a directory and dir/package.json exist, execute as is
# if not, or if there is no argument, prepend `pwd` to the arguments
if [ $# -ge 1 -a -d "$1" -a -f "$1/package.json" ]
then
        # node-webkit wants a full path for the package
#       case $1 in
#               /*) PACKAGE=$1 ;;
#               *) PACKAGE=`pwd`/$1 ;;
#       esac
# Do this instead because otherwise the app protocol does not seem to work!
        cd $1
        PACKAGE=`pwd`
###
        shift
        open -n "$NWAPP" --args "$PACKAGE" $*
else
        open -n "$NWAPP" --args `pwd` $*
fi
