#!/bin/bash
#
# run the WildOS server
# 	wildos [start] [-w|--wall config] [-p|--port number] [app ...]
#	wildos stop

DIR=`which $0`
DIR=`dirname $DIR`
case $DIR in
	/*) ;;
	*) DIR=`pwd`/$DIR ;;
esac

NW=$DIR/nw_wrapper

if [ $# -eq 0 ]; then
	set start
fi

# clean up
case $1 in
	stop)
		# avoid killall nwjs on local machine as it will kill the server too!
		if [ $MACHINE == 'Linux' ]; then 
			ps aux | fgrep /nw | fgrep -v server | fgrep -v -- --type= | awk '{print $2}' | xargs kill || true
		else
			# Mac OS X
			kill `ps -e | grep nwjs | grep instance | awk '{print $1}'` || true
		fi

		if [ "$WALL" != 'local' ]; then
			$DIR/walldo killall nw
		fi
	;;
	start)
		shift
		$NW $DIR/../server $*
	;;
	*)
		$NW $DIR/../server $*
	;;
esac
